"Resource/LoadingDialog.res"
{
	"LoadingDialog"
	{
		"ControlName"			"Frame"
		"fieldName"				"LoadingDialog"
		"xpos"					"r410"
		"ypos"					"b80"
		"wide"					"400"
		"tall"					"65"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"settitlebarvisible"	"0"
		"title"					"0"

		"bgcolor_override"		"10 10 14 230"
	}
	"InfoLabel"
	{
		"ControlName"			"Label"
		"fieldName"				"InfoLabel"
		"xpos"					"12"
		"ypos"					"6"
		"wide"					"376"
		"tall"					"20"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"#GameUI_ParseBaseline"
		"textAlignment"			"west"
		"dulltext"				"0"
		"brighttext"			"1"

		"defaultFgColor_override"	"210 215 225 255"
	}
	"progress"
	{
		"ControlName"			"ProgressBar"
		"fieldName"				"Progress"
		"xpos"					"10"
		"ypos"					"33"
		"wide"					"310"
		"tall"					"22"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"paintborder"			"0"

		"fgcolor_override"		"35 135 237 255"
		"bgcolor_override"		"20 28 50 160"
	}
	"CancelButton"
	{
		"ControlName"			"Button"
		"fieldName"				"CancelButton"
		"xpos"					"324"
		"ypos"					"33"
		"wide"					"66"
		"tall"					"22"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"#GameUI_Cancel"
		"textAlignment"			"center"
		"dulltext"				"0"
		"brighttext"			"0"
		"command"				"Cancel"
		"Default"				"0"

		"defaultFgColor_override"		"210 215 225 255"
		"defaultBgColor_override"		"20 28 50 180"
		"armedFgColor_override"			"255 255 255 255"
		"armedBgColor_override"			"35 135 237 90"
		"depressedFgColor_override"		"255 255 255 255"
		"depressedBgColor_override"		"35 135 237 180"
	}
	"CopyButton"
	{
		"ControlName"			"Button"
		"fieldName"				"CopyButton"
		"xpos"					"256"
		"ypos"					"33"
		"wide"					"66"
		"tall"					"22"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"#GameUI_Copy"
		"textAlignment"			"center"
		"dulltext"				"0"
		"brighttext"			"0"
		"command"				"Copy"
		"Default"				"0"

		"defaultFgColor_override"		"210 215 225 255"
		"defaultBgColor_override"		"20 28 50 180"
		"armedFgColor_override"			"255 255 255 255"
		"armedBgColor_override"			"35 135 237 90"
	}
	"Divider1"
	{
		"ControlName"		"Divider"
		"fieldName"			"Divider1"
		"xpos"				"20"
		"ypos"				"104"
		"wide"				"340"
		"tall"				"2"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"0"
		"enabled"			"1"
		"tabPosition"		"0"
	}
	"Label1"
	{
		"ControlName"		"Label"
		"fieldName"			"Label1"
		"xpos"				"20"
		"ypos"				"109"
		"wide"				"340"
		"tall"				"24"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"0"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"#GameUI_LoadingDialog_ContentHosting"
		"textAlignment"		"west"
		"dulltext"			"1"
		"brighttext"		"0"

		"defaultFgColor_override"	"140 145 155 180"
	}
	"BannerAd"
	{
		"ControlName"		"HTML"
		"fieldName"			"BannerAd"
		"xpos"				"20"
		"ypos"				"136"
		"wide"				"340"
		"tall"				"56"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"0"
		"enabled"			"1"
		"tabPosition"		"0"
	}
	"SecondaryProgressLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"SecondaryProgressLabel"
		"xpos"				"20"
		"ypos"				"90"
		"wide"				"260"
		"tall"				"24"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"0"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"Label"
		"textAlignment"		"west"
		"dulltext"			"1"
		"brighttext"		"0"

		"defaultFgColor_override"	"140 145 155 180"
	}
	"Progress2"
	{
		"ControlName"		"ProgressBar"
		"fieldName"			"Progress2"
		"xpos"				"20"
		"ypos"				"114"
		"wide"				"260"
		"tall"				"24"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"0"
		"enabled"			"1"
		"tabPosition"		"0"

		"fgcolor_override"	"35 135 237 255"
		"bgcolor_override"	"20 28 50 160"
	}
	"TimeRemainingLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"TimeRemainingLabel"
		"xpos"				"20"
		"ypos"				"108"
		"wide"				"260"
		"tall"				"24"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"0"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			""
		"textAlignment"		"west"
		"dulltext"			"1"
		"brighttext"		"0"

		"defaultFgColor_override"	"140 145 155 180"
	}
}
